# -*- cmake -*-
if( STANDALONE )
	include( FindXmlRpcEpi )
	set(XMLRPCEPI_INCLUDE_DIRS ${XMLRPCEPI_INCLUDE_DIR})
else( STANDALONE )
	if (WINDOWS)
		set(XMLRPCEPI_LIBRARIES_BASENAME xmlrpcepi.lib)
		set(XMLRPCEPI_LIBRARIES
			debug ${ARCH_PREBUILT_DIRS_DEBUG}/${XMLRPCEPI_LIBRARIES_BASENAME}
			optimized ${ARCH_PREBUILT_DIRS_RELEASE}/${XMLRPCEPI_LIBRARIES_BASENAME} )
	else (WINDOWS)
		set(XMLRPCEPI_LIBRARIES xmlrpc-epi)
	endif (WINDOWS)

	set(XMLRPCEPI_INCLUDE_DIRS ${LIBS_PREBUILT_DIR}/include)
endif( STANDALONE )
